initial commit
fox-it/dissect.jffs pull request #1
Opened 2023-10-16 11:15 UTC by JSCU-CNI

This PR adds the initial version of the Dissect JFFS2 parser.

2023-10-18 13:19 UTC, Schamper commented on README.md
> +Dissect JFFS parser is developed and released as open source by the Joint Sigint Cyber Unit (<https://github.com/JSCU-NL>)
```suggestion
`dissect.jffs` is developed and released as open source by the Joint Sigint Cyber Unit (<https://github.com/JSCU-NL>)
```
Maybe? To put more emphasis on this project.

2023-10-18 13:20 UTC, Schamper commented on dissect/jffs/jffs2.py
> +log = logging.getLogger(__name__)
You could maybe add something similar like this: https://github.com/fox-it/dissect.hypervisor/blob/main/dissect/hypervisor/disk/vmdk.py#L22

2023-10-18 13:21 UTC, Schamper commented on dissect/jffs/jffs2.py
> +            # Traverse to the target path from our root node
```suggestion
```
Comment seems misplaced

2023-10-18 13:22 UTC, Schamper commented on dissect/jffs/jffs2.py
> +        for part in parts:
There's no symlink resolution yet. This doesn't matter a whole lot for usage in `dissect.target` (where we do it in the `RootFilesystem`), but do you want to/intend to add it in the future?

2023-10-18 13:24 UTC, Schamper commented on dissect/jffs/jffs2.py
> +            for name, entry in node.iterdir():
I think you could cheat a little bit and make this a lot faster by doing direct lookups of the (byte encoded) part in `self._dirents`. But I'll leave the decision up to you if you think that's worth complicating the code for :smile:

2023-10-18 13:30 UTC, Schamper commented on dissect/jffs/jffs2.py
> +        return self.inode.atime * 1_000_000_000
I'm not sure these add much, perhaps use `ts.from_unix(self.inode.atime)` in the respective non-ns variants of these methods?

2023-10-18 13:32 UTC, Schamper commented on pyproject.toml
> +license-files = ["LICENSE", "COPYRIGHT"]
The COPYRIGHT file is currently missing?

2023-10-18 14:06 UTC, Schamper commented on README.md
> +A Dissect module implementing a parser for the JFFS2 file system. For more
```suggestion
A Dissect module implementing a parser for the JFFS2 file system, commonly used by router operating systems. For more
```

2023-10-18 14:44 UTC, JSCU-CNI commented on README.md
> +information, please see [the documentation](https://docs.dissect.tools/en/latest/projects/dissect.jffs/index.html).
Yes, created a PR: https://github.com/fox-it/dissect-docs/pull/33

2023-10-18 15:12 UTC, JSCU-CNI commented on dissect/jffs/jffs2.py
> +        for part in parts:
That's an oversight on our part and definitely something we would like to have in `dissect.jffs`.

2023-10-18 15:14 UTC, JSCU-CNI commented on dissect/jffs/jffs2.py
> +            for name, entry in node.iterdir():
The current setup could indeed be a bit faster, however this follows the generic approach of other filesystem implementations so we feel this would be a more uniform approach.

2023-10-18 15:22 UTC, JSCU-CNI commented on dissect/jffs/jffs2.py
> +        return self.inode.atime * 1_000_000_000
This is someting we copied from `dissect.ffs` or `dissect.extfs` I believe. JFFS2 inodes/dirents do not store extra precision timestamp information. Are the `*_ns` properties required for other parts in Dissect, or can we remove them altogether?

2023-10-18 15:24 UTC, JSCU-CNI commented on pyproject.toml
> +license-files = ["LICENSE", "COPYRIGHT"]
Added in [d00e3e6](https://github.com/fox-it/dissect.jffs/pull/1/commits/d00e3e67ca10110a028b55e0f236d633c1e184d8)

2023-10-18 15:25 UTC, JSCU-CNI commented on dissect/jffs/jffs2.py
> +log = logging.getLogger(__name__)
Added in [d00e3e6](https://github.com/fox-it/dissect.jffs/pull/1/commits/d00e3e67ca10110a028b55e0f236d633c1e184d8).

2023-10-18 15:38 UTC, Schamper commented on dissect/jffs/jffs2.py
> +        return self.inode.atime * 1_000_000_000
They are presed in `ffs` and `extfs` because sometimes there are nanosecond accuracy timestamps, but since JFFS does not have any, they don't add anything.

If present, they can be added to the `.stat()` output, but again, since JFFS doesn't have any, this wouldn't add anything: https://github.com/fox-it/dissect.target/blob/main/dissect/target/filesystems/ffs.py#L129-L132

2023-10-18 15:43 UTC, Schamper commented on dissect/jffs/jffs2.py
> +        for part in parts:
You can look at some of the code in `dissect.ffs` on how to achieve this. Don't try to think too hard about cross-filesystem symlinks :smile: that's handled in `dissect.target`.

2023-10-18 16:31 UTC, JSCU-CNI commented on dissect/jffs/jffs2.py
> +        return self.inode.atime * 1_000_000_000
Thanks for clarifying! Removed in [469cbe0](https://github.com/fox-it/dissect.jffs/pull/1/commits/469cbe05ba184012399dbaaa5f83165c55c5f383).

2023-10-30 15:44 UTC, JSCU-CNI commented on dissect/jffs/jffs2.py
> +            for name, entry in node.iterdir():
I've attempted to implement this in [3bb66c3](https://github.com/fox-it/dissect.jffs/pull/1/commits/3bb66c3564a17df39588acd9abe747e89f4f1f6b). Please let me know if this seems OK :)

2023-10-30 15:48 UTC, JSCU-CNI commented on dissect/jffs/jffs2.py
> +        for part in parts:
So if we would add the following two lines at line 76 in `jffs2.py` @ [3bb66c3](https://github.com/fox-it/dissect.jffs/pull/1/commits/3bb66c3564a17df39588acd9abe747e89f4f1f6b)
```python
while node.type == stat.S_IFLNK and part_num < len(parts):
    node = node.link_inode
```

This causes a number of things to change in for example target-shell and our tests, as the resolved dirents/inodes are no longer seen as a symlink. Would this require changes in our `dissect.target.filesystems.jffs` `FilesystemEntry` implementation? I can't really quickly figure out how `dissect.ffs` deals with this.

To illustrate:

```
# before
jffs2.bin /foo/bar> ls -la
-rwxrwxrwx    0    0      9 2023-06-23T20:28:10 link.txt -> /test.txt

# after
jffs2.bin /> ls foo/bar -la
-rw-r--r--    0    0      9 2023-06-23T20:27:20 link.txt
```

2023-10-30 16:56 UTC, Schamper commented on dissect/jffs/jffs2.py
> +        for part in parts:
I now see that `dissect.ffs` still has the unnecessary `part_num` check, but the principle stays the same. 

You only check if the current node is a symlink, not if the node you're navigating to is one. So if we write out an example layout

```
/file.txt
/foo -> /bar
/bar/file.txt -> /file.txt
```

And we're trying to reach `/foo/file.txt`, we end up with the following iterations for each path component:
- current path = `/`, trying to get `foo`
  - node = `root,` check if node is a symlink (it's not)
  - node = `/foo`
- current path = `/foo`, trying to get `file.txt`
  - node = `/foo,` check if node is a symlink (it is, resolve to `/bar`)
  - node = `/bar/file.txt`
- loop exit because we exhausted path components

As you can see, we never resolve the symlink for `/bar/file.txt` because we have already exited the loop. We will return the `/bar/file.txt` node which will correctly report as a symlink.

2023-10-30 17:10 UTC, Schamper requested changes

2023-10-30 17:10 UTC, Schamper commented on dissect/jffs/jffs2.py
> +        parts = path.split("/")
```suggestion
        parts = path.encode().split(b"/")
```
So we don't have to encode each individual part in the loop.

2023-10-30 17:10 UTC, Schamper commented on dissect/jffs/jffs2.py
> +        for part_num, part in enumerate(parts):
```suggestion
        for part in parts:
```
Sorry for the misguided suggestion of looking at `dissect.ffs` :smile:

2023-10-30 17:10 UTC, Schamper commented on dissect/jffs/jffs2.py
> +                raise FileNotFoundError(f"File not found: {path}")
```suggestion
            if dirent := self._dirents[node.inum].get(part):
                node = self.inode(dirent[-1].inum)
                # TODO: symlinks
            else:
                raise FileNotFoundError(f"File not found: {path}")
```
I did not test this, so please verify. IIRC `self._dirents` is a mapping of `(ino) => (name of entries)`, so you should be able to index directly into the `self._dirents` dict with the current node `inum`, and then directly index into that with the current part name. If no part name exists then the path is invalid.

I did not understand why the `if dirent[-1].parent_inum == node.inum:` was necessary, but it's probably a JFFS2 specific thing I overlooked?

You can also chose to sort the directory entries by version like you currently do in `iterdir()`. In fact, it might be nice to do that during the parsing phase? Or do sorted inserts using `bisect`.

2023-10-30 17:11 UTC, Schamper commented on dissect/jffs/jffs2.py
> +            for dirent_children in self._dirents.values():
For reference, you'd put the symlink check for `node` in between this `if` and `for`.

2023-10-30 17:13 UTC, Schamper commented on dissect/jffs/jffs2.py
> +            for name, entry in node.iterdir():
Left some comments ;)

2023-11-01 12:40 UTC, JSCU-CNI commented on dissect/jffs/jffs2.py
> +                raise FileNotFoundError(f"File not found: {path}")
Thanks for the suggestion, added in [3d6e94c](https://github.com/fox-it/dissect.jffs/pull/1/commits/3d6e94c7ecc4da0c5b7acf659403413ade882143). This indeed seems to work, the check on `parent_inum == node.inum` was too stringent and turned out to not be necessary.

2023-11-01 12:40 UTC, JSCU-CNI commented on dissect/jffs/jffs2.py
> +        for part in parts:
Thanks for explaining. This indeed makes more sense.

2023-11-02 20:07 UTC, Schamper commented on dissect/jffs/jffs2.py
> +                raise FileNotFoundError(f"File not found: {path}")
Thanks, that looks good. My last remaining comment would be the last sentence in the last comment:

> You can also chose to sort the directory entries by version like you currently do in iterdir(). In fact, it might be nice to do that during the parsing phase? Or do sorted inserts using bisect.

I'll leave it up to you if you wish to proceed down this road. I can implement this part if you need.

2023-11-06 10:48 UTC, JSCU-CNI commented on dissect/jffs/jffs2.py
> +                raise FileNotFoundError(f"File not found: {path}")
Just so we understand correctly, you want to sort all `DirEntry`s by the `version` attribute in the list `self._dirents[pino][b"name"]`? If so, sorting would be neat, but perhaps unnecessary. Due to JFFS2 being a log/journal-based filesystem we currently assume the last `DirEntry` we encounter is also the latest version.

2023-11-06 16:06 UTC, Schamper commented
The `.github` directory seems to be missing currently, so there's no CI. Could you add that?

2023-11-07 08:55 UTC, Schamper requested changes

2023-11-07 08:55 UTC, Schamper commented on .github/dissect-ci.yml
Can you move this to `.github/workflows/dissect-ci.yml`?

2023-11-08 11:28 UTC, Schamper commented on dissect/jffs/jffs2.py
> +                raise FileNotFoundError(f"File not found: {path}")
I've added the sorting just in case in https://github.com/fox-it/dissect.jffs/pull/1/commits/9b4f7d315afe179097b98e34ec3c70f3465c1e28, because I see other implementations doing something similar (dropping older versions).

I don't have any huge JFFS2 images, so I'm not sure what the performance implications are. If it's large, we can do something more optimistic (only ensure the last entry is the latest, leave the rest unsorted).

2023-11-08 11:29 UTC, Schamper commented
I've added the sorting just in case in https://github.com/fox-it/dissect.jffs/pull/1/commits/9b4f7d315afe179097b98e34ec3c70f3465c1e28, because I see other implementations doing something similar (dropping older versions).

I don't have any huge JFFS2 images, so I'm not sure what the performance implications are. If it's large, we can do something more optimistic (only ensure the last entry is the latest, leave the rest unsorted).

Let me know if you agree with this, then this should be good to go.

2023-11-08 20:38 UTC, Schamper submitted a review, later dismissed

2023-11-13 10:14 UTC, JSCU-CNI commented
LGTM!

2023-12-08 15:34 UTC, Schamper approved these changes

2023-12-08 17:43 UTC, merged